Add Talisman to README
polkadot-js/phishing pull request #3050
Opened 2023-02-27 00:41 UTC by jonathanpdunne

2023-02-27 06:13 UTC, jacogr commented on README.md
> +- [Talisman](https://talisman.xyz)
Please just follow the comment pre-ceding the addition above.

2023-02-27 06:16 UTC, jacogr requested changes
Please correct the ordering as per the comment in the "note to editors".

2023-03-06 00:36 UTC, jonathanpdunne commented
> Please correct the ordering as per the comment in the "note to editors".

Rectified.

2023-03-06 04:31 UTC, jacogr approved these changes

2023-03-06 04:31 UTC, merged